/* Copyright 2016-2017 INRIA and Microsoft Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file was auto-generated by KreMLin! */

#include "FStar.h"

static uint64_t
FStar_UInt128_constant_time_carry(uint64_t a, uint64_t b)
{
    return (a ^ ((a ^ b) | ((a - b) ^ b))) >> (uint32_t)63U;
}

static uint64_t
FStar_UInt128_carry(uint64_t a, uint64_t b)
{
    return FStar_UInt128_constant_time_carry(a, b);
}

FStar_UInt128_uint128
FStar_UInt128_add(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low + b.low;
    c.high = a.high + b.high + FStar_UInt128_carry(a.low + b.low, b.low);
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_add_mod(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low + b.low; 
    c.high = a.high + b.high + FStar_UInt128_carry(a.low + b.low, b.low);
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_sub(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low - b.low;
    c.high = a.high - b.high - FStar_UInt128_carry(a.low, a.low - b.low);
    return c;
}

static FStar_UInt128_uint128
FStar_UInt128_sub_mod_impl(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low - b.low;
    c.high = a.high - b.high - FStar_UInt128_carry(a.low, a.low - b.low);
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_sub_mod(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    return FStar_UInt128_sub_mod_impl(a, b);
}

FStar_UInt128_uint128
FStar_UInt128_logand(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low & b.low;
    c.high = a.high & b.high;
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_logxor(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low ^ b.low;
    c.high = a.high ^ b.high;
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_logor(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low | b.low;
    c.high = a.high | b.high;
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_lognot(FStar_UInt128_uint128 a)
{
    FStar_UInt128_uint128 c = {0};
    c.low = ~a.low;
    c.high = ~a.high;
    return c;
}

static uint32_t FStar_UInt128_u32_64 = (uint32_t)64U;

static uint64_t
FStar_UInt128_add_u64_shift_left(uint64_t hi, uint64_t lo, uint32_t s)
{
    return (hi << s) + (lo >> (FStar_UInt128_u32_64 - s));
}

static uint64_t
FStar_UInt128_add_u64_shift_left_respec(uint64_t hi, uint64_t lo, uint32_t s)
{
    return FStar_UInt128_add_u64_shift_left(hi, lo, s);
}

static FStar_UInt128_uint128
FStar_UInt128_shift_left_small(FStar_UInt128_uint128 a, uint32_t s)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.low << s;
    c.high = FStar_UInt128_add_u64_shift_left_respec(a.high, a.low, s);
    if (s == (uint32_t)0U)
        return a;
    else
        return c;
}

static FStar_UInt128_uint128
FStar_UInt128_shift_left_large(FStar_UInt128_uint128 a, uint32_t s)
{
    FStar_UInt128_uint128 c = {0};
    c.low = (uint64_t)0U;
    c.high = a.low << (s - FStar_UInt128_u32_64);
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_shift_left(FStar_UInt128_uint128 a, uint32_t s)
{
    if (s < FStar_UInt128_u32_64)
        return FStar_UInt128_shift_left_small(a, s);
    else
        return FStar_UInt128_shift_left_large(a, s);
}

static uint64_t
FStar_UInt128_add_u64_shift_right(uint64_t hi, uint64_t lo, uint32_t s)
{
    return (lo >> s) + (hi << (FStar_UInt128_u32_64 - s));
}

static uint64_t
FStar_UInt128_add_u64_shift_right_respec(uint64_t hi, uint64_t lo, uint32_t s)
{
    return FStar_UInt128_add_u64_shift_right(hi, lo, s);
}

static FStar_UInt128_uint128
FStar_UInt128_shift_right_small(FStar_UInt128_uint128 a, uint32_t s)
{
    FStar_UInt128_uint128 c = {0};
    c.low = FStar_UInt128_add_u64_shift_right_respec(a.high, a.low, s);
    c.high = a.high >> s; 
    if (s == (uint32_t)0U)
        return a;
    else
        return c;
}

static FStar_UInt128_uint128
FStar_UInt128_shift_right_large(FStar_UInt128_uint128 a, uint32_t s)
{
    FStar_UInt128_uint128 c = {0};
    c.low = a.high >> (s - FStar_UInt128_u32_64);
    c.high = (uint64_t)0U;
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_shift_right(FStar_UInt128_uint128 a, uint32_t s)
{
    if (s < FStar_UInt128_u32_64)
        return FStar_UInt128_shift_right_small(a, s);
    else
        return FStar_UInt128_shift_right_large(a, s);
}

FStar_UInt128_uint128
FStar_UInt128_eq_mask(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = FStar_UInt64_eq_mask(a.low, b.low) & FStar_UInt64_eq_mask(a.high, b.high);
    c.high = FStar_UInt64_eq_mask(a.low, b.low) & FStar_UInt64_eq_mask(a.high, b.high);
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_gte_mask(FStar_UInt128_uint128 a, FStar_UInt128_uint128 b)
{
    FStar_UInt128_uint128 c = {0};
    c.low = (FStar_UInt64_gte_mask(a.high, b.high) & ~FStar_UInt64_eq_mask(a.high, b.high)) | (FStar_UInt64_eq_mask(a.high, b.high) & FStar_UInt64_gte_mask(a.low, b.low));
    c.high = (FStar_UInt64_gte_mask(a.high, b.high) & ~FStar_UInt64_eq_mask(a.high, b.high)) | (FStar_UInt64_eq_mask(a.high, b.high) & FStar_UInt64_gte_mask(a.low, b.low));
    return c;
}

FStar_UInt128_uint128
FStar_UInt128_uint64_to_uint128(uint64_t a)
{
    FStar_UInt128_uint128 c = {0};
    c.low = (uint64_t) a;
    c.high = (uint64_t) 0U;
    return c;
}

uint64_t
FStar_UInt128_uint128_to_uint64(FStar_UInt128_uint128 a)
{
    return a.low;
}

static uint64_t FStar_UInt128_u64_l32_mask = (uint64_t)0xffffffffU;

static uint64_t
FStar_UInt128_u64_mod_32(uint64_t a)
{
    return a & FStar_UInt128_u64_l32_mask;
}

static uint32_t FStar_UInt128_u32_32 = (uint32_t)32U;

static uint64_t
FStar_UInt128_mul_wide_impl_t_(uint64_t x, uint64_t y)
{
    uint64_t fst;
    uint64_t snd;
    uint64_t thd;
    uint64_t f3;
    uint64_t finalval;
    fst = x;
    snd = ((uint64_t) FStar_UInt128_u64_mod_32(FStar_UInt128_u64_mod_32(x) * FStar_UInt128_u64_mod_32(y)));
    thd = ((uint64_t) x >> FStar_UInt128_u32_32);
    f3 = ((uint64_t) (x >> FStar_UInt128_u32_32) * FStar_UInt128_u64_mod_32(y) + (FStar_UInt128_u64_mod_32(x) * FStar_UInt128_u64_mod_32(y) >> FStar_UInt128_u32_32));
    finalval = fst, snd, thd, f3;
    return finalval;
}

static uint64_t
FStar_UInt128_u32_combine_(uint64_t hi, uint64_t lo)
{
    return lo + (hi << FStar_UInt128_u32_32);
}

static FStar_UInt128_uint128
FStar_UInt128_mul_wide_impl(uint64_t x, uint64_t y)
{
    uint64_t scrut = FStar_UInt128_mul_wide_impl_t_(x, y);
    uint64_t fst;
    uint64_t snd;
    uint64_t thd;
    uint64_t f3;
    uint64_t u1 = fst;
    uint64_t w3 = snd;
    uint64_t x_ = thd;
    uint64_t t_ = f3;
    FStar_UInt128_uint128 finalval;
    finalval.low = FStar_UInt128_u32_combine_(u1 * (y >> FStar_UInt128_u32_32) + FStar_UInt128_u64_mod_32(t_),
                                              w3);
    finalval.high = x_ * (y >> FStar_UInt128_u32_32) + (t_ >> FStar_UInt128_u32_32) +
                    ((u1 * (y >> FStar_UInt128_u32_32) + FStar_UInt128_u64_mod_32(t_)) >> FStar_UInt128_u32_32);
    return finalval;
}

FStar_UInt128_uint128
FStar_UInt128_mul_wide(uint64_t x, uint64_t y)
{
    return FStar_UInt128_mul_wide_impl(x, y);
}
