$inherits:
  from: 'tasks/build.yml'
  variables:
    build_name: 'macosx64'
    build_type: 'opt'
task:
  metadata:
      name: '[TC] MacOSX64 Opt'
      description: 'MacOSX64 Opt'

  workerType: opt-macosx64

  routes:
    - 'index.buildbot.branches.{{project}}.macosx64'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.macosx64'

  scopes:
    - 'docker-worker:cache:build-macosx64-workspace'
    - 'docker-worker:cache:tooltool-cache'

  payload:
    image: '{{#docker_image}}desktop-build{{/docker_image}}'
    cache:
      build-macosx64-c6-workspace: '/home/worker/workspace'
      tooltool-cache: '/home/worker/tooltool-cache'
    features:
      relengAPIProxy: true

    env:
      MOZHARNESS_SCRIPT: 'mozharness/scripts/fx_desktop_build.py'
      MOZHARNESS_CONFIG: 'builds/releng_base_mac_cross_builds.py balrog/production.py'
      MH_BRANCH: {{project}}
      MH_BUILD_POOL: taskcluster
      #TODO: bug 1164617 - remove Docker image hacks
      LIBRARY_PATH: ""
      CPLUS_INCLUDE_PATH: ""
      # image paths
      TOOLTOOL_CACHE: '/home/worker/tooltool-cache'
      DIST_UPLOADS: 'jsshell-mac.zip'
      DIST_TARGET_UPLOADS: 'x-test.mac.tar.bz2 mac.dmg mac.json tests.zip crashreporter-symbols.zip'

    maxRunTime: 36000

    command: ["/bin/bash", "bin/build.sh"]

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      machine:
        # see https://github.com/mozilla/treeherder/blob/master/ui/js/values.js
        platform: macosx64
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.mac.dmg'
      tests: 'public/build/target.tests.zip'
